Financial-Times/o-share

src/scss/_functions.scss

Probably only happening with libsass - but $_o-share-sprite-elements is an array, not a map
/cc @kaelig @AlbertoElias

Fix icons being included twice in sprite

---

src/js/share.js

Twitter intents (https://dev.twitter.com/web/intents) parses the page for twitter links, and adds event handlers for showing a popup. o-share does the same, the result being 2 popups open (with any twitter widget on the page).
This is the case on AV2 as well, where we have a twitter widget in the right hand rail (https://ftalphaville2-test.ft.com/content/7b4b3d5d-514c-334d-b5f3-8bd8e24d349e). Preventing the propagation of the events on the link fixes the issue.

Fix the double popup when Twitter intents is loaded on the page.

---

src/js/share.js

Do the same for Facebook although facebook doesn't seem to use the title.

URL-encode the pipe character in LinkedIn URL to prevent "HTTP Error" messages from LinkedIn when sharing items with "Extra" set

---

bower.json
main.scss
src/scss/share.scss

Button size is now at `40px` square including borders and has a hit area of `45px` at default, increasing to `50px` from small up.
Also fixes an issue with black icons not appearing in Windows high-contrast mode. Sets icon to white and forces a black background which is not changed when Windows is using any high-contrast theme. Tested in both Windows and Mac high-contrast modes thanks to @lc512k 
Closes #59

Fix sizing issue and high contrast usage

---

src/js/share.js

Although the API is supported, it only takes one argument at a time, so the action type wasn't being added.
http://caniuse.com/#search=classlist

Add individual classnames with `classList.add()` for IE11

---

demos/src/inverse.mustache
demos/src/main.mustache
demos/src/pa11y.mustache
src/scss/share.scss

This adds a class to `a` and `button` elements, to avoid sizing conflicts with other components (e.g. [this issue](https://github.com/Financial-Times/o-tooltip/pull/21) with `o-tooltip`)

icon specificity

---

src/js/share.js

Passing the window object of the page which opened the social sharing site makes us susceptible to phishing and XSS attacks.
E.G. Code the social sharing sites could use to attack us.
```js
// window.opener would be the window object of the page the user clicked the sharing button on, probably an ft article.
if (window.opener) {
window.opener.location = 'https://www.ft.com.example.com' // Fake FT login page to steal users credentials
}
```

Do not pass the opener window object to the new page

---

demos/src/inverse.mustache
demos/src/pa11y.mustache
src/js/share.js

This is just removing bits that facebook won't recognise anymore, but it seems like @jkerr321 already updated the docs in https://github.com/Financial-Times/o-share/commit/d6a60727935efcd288aefe7e41660655dbd285b3.
Closes #98

remove superfluous params

---

demos/src/inverse.mustache
demos/src/main.mustache
src/scss/_color-use-cases.scss
src/scss/_variables.scss
src/scss/share.scss

This doesn't need the full "copy a URL" functionality, but it's used to
link to video pages on the FT.com home page and its disappearance is
holding up their work.
Resolves #111

Re-add the link icon

---

demos/src/pa11y.mustache

Other links don't actually have `target="_blank"` set so I've left them alone.

Better link text when opening in a new window

---

demos/src/demo.scss
src/scss/share.scss

We no longer support the browsers which required this fallback

Remove PNG fallback for SVG background-image

---

demos/src/data-vertical.json
demos/src/data.json
demos/src/demo.scss
demos/src/inverse.mustache
demos/src/main.mustache
demos/src/pa11y.mustache
src/scss/_color-use-cases.scss
src/scss/_variables.scss
src/scss/share.scss

In next-article, we want to use the share icon instead of the link icon.
The changes in this PR are what I think is necessary to support this.

Support "share" icon as well as "mail" & "link"

---

README.md
demos/src/data-vertical.json
demos/src/data.json
src/js/share.js

Removes references to Google Plus which is shutting down. It will be [removed in the next major](https://github.com/Financial-Times/o-share/issues/new). I chose not to output deprecation warnings as customers with silent mode off may feel spammed -- it's not a difficult migration with the next major.

Remove references to Google Plus.

---

src/scss/_color-use-cases.scss
src/scss/share.scss

In response to our [DAC Accessibility Audit Report](https://docs.google.com/spreadsheets/d/1_Wp100e-2gwGQDxPS6YODqFsVRwycO9Y6PiXzppU-TY/edit#gid=2122682530).
before / after

Darken social share border to improve contrast.

---

README.md
src/js/share.js

The `oShare.open` and `oShare.ready` events were not documented.
_Some indentation has also been corrected_

Improve o-share JSDoc and event documentation.

---

src/js/share.js

JsDoc is not actually escaping the namespace "." char. It is
actually including a backslash in the namespace.
Instead [use quotes](https://devdocs.io/jsdoc/about-namepaths).
Before: `"longname": "oShare\\.event:open",`
After: `"longname": "event:\"oShare.open\"",`

Remove escape char from JsDoc event names.

---

src/js/share.js

To support show/hide functionality at the list-item level. 
The whatsapp share icon should only be visible on smaller viewports. This change allows us to target the element at the list-item level and to have the show/hide behaviour persist when user-navigation causes the share icons to be refreshed.

add a new action class at the list element level

---

src/js/share.js

To support a refactor of the share links into a single list in the video section of the front page.
Adding 'link' as a sociallUrl allows us to treat all video share links consistently. This simplifies the share icons code and ensures greater visual consistency between the icons.

add link to the list of valid socialUrls

---

src/js/share.js
test/Share.test.js

This will encode the url that is passed to the social platforms.
As the url is used within the sharing url it is important to encode otherwise
if the url contains items such as a hash it will terminate the parsing
of the share url at that stage and miss anything after the hash.
eg.
`https://twitter.com/intent/tweet?url=https://www.ft.com/content/1581cbdb-c47e-3073-b629-017397a981e5#post-44945&text=Example%20Title&related=&via=FT`
When this url is parsed it will think all of this is part of the hash
`#post-44945&text=Example%20Title&related=&via=FT`

Adds encoding to the url before sharing

---

test/Share.test.js
test/origami.test.js

Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.

Stop using magic webpack imports

---

src/js/share.js
test/Share.test.js

Adds descriptive text to the links when the markup is not provided for the social links and therefore the component is only being used in an enhanced experience manor.
This will improve the accessibility of this component as users of screen readers will hear what the intent of using these links will know that they open in a new window.
Its worth highlighting here that this component has a "link" social option in this
component is an edge case that already behaves  in a possibly unexpected way. Clicking this option will just open the link in a new window, it doesn't do anything like copy to clipboard. For this reason this option needs its own and different descriptive text which is still not overly helpful.
`target="_blank"` and `rel="noopener"` attributes were also added to the anchors as …

Adds descriptive text to links for accessibility

---

src/scss/share.scss

Stop the background image from repeating when the element has a larger dimension in one direction.
This has happening on FT.com articles because of some hacky css overrides.
This fix doesn't solve all the issues on FT.com but to me it does seem like a sensible property to have in place anyway and it will fix initial visual defect on ft.com
**Before**
**After**

Prevents the background image from repeating

---

README.md
src/js/share.js

Adding the `data-o-share-location` option to the root element will allow
the tracking requests to include a location identifier.
This will be useful when multiple share components exist on a single
page and we want to know which is generating clicks.

Adds a location option for tracking

---

README.md
demos/src/data-custom.json
demos/src/data-inverse.json
demos/src/data-small.json
demos/src/data-vertical.json
demos/src/main.mustache
demos/src/pa11y.mustache
main.scss
origami.json
src/scss/_brand.scss
src/scss/_color-use-cases.scss
src/scss/_mixins.scss
src/scss/_variables.scss

**Remove `bookmark-outline` (before release)**
The share button on ft.com is currently a n-myft-ui button with
extra styles and behaviour attached, so no one will be using
`bookmark-outline`.
**Add new custom colour usecases.**
This will let users like next-article match o-share colours
more accurately to override n-myft-ui save icon colours 😷
Financial-Times/next-article#3796
**Add `$o-share-border-style` variable**
So next-article can more accurately override the n-myft-ui save icon
to match o-share 😷
https://github.com/Financial-Times/next-article/pull/3796/files

Label support extra

---

src/js/share.js
test/Share.test.js

Through the DAC audit, we learned that the share components on the home
page do not have descriptive enough link text. DAC recommends adding
the title of the video to the link text. The share components are used
on a few apps (e.g. `next-article`) so I thought it might make more
sense to update the descriptive link text in `o-share` rather than in
each individual app.
Please let me know if you think this is appropriate! I tested it using 
`next-front-page` and it looks like the changes work:
[DAC ticket](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1153&projectKey=CI&modal=detail&selectedIssue=CI-183)

CI-183 Add title to the social descriptive link text

---

demos/src/demo.js
main.js
test/Share.test.js
test/origami.test.js

relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing

add extension to relative imports to make the code work directly in a browser

---

origami.json
src/scss/_brand.scss

We need to state explicitly the brands which are supported because the default supported brands if no `brands` field is supplied is `master`.
This change will allow internal branded products such as the new wordpress theme to use o-share

State o-share supports masteer and internal brands 

---

demos/src/data-custom.json
demos/src/data-inverse.json
demos/src/data-small.json
demos/src/data-vertical.json
demos/src/data.json
demos/src/main.mustache
demos/src/pa11y.mustache
main.scss
origami.json
src/js/share.js
src/scss/_variables.scss

We have a new sharing platform, the new enterprise super gift product. This pull request adds the corporate icon into o-share to be used for this new sharing product.
Here is the link to the design for this -- https://www.figma.com/proto/Tun2MN4GA77UeUQUUXvXas/Super-Gifting---Main-File?node-id=552%3A1314&scaling=min-zoom
Here is a screenshot of the new share button/link in the list
Here is a screenshot showing the hover/focus states of the share buttons/links

Make the new corporate icon from fticons available in o-share
